name: label-studio-be
channels:
  - pytorch
  - nvidia
  - conda-forge
  - default
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - gunicorn
  - rq
  - timm
  - pyyaml
  - shapely
  - pip
  - pip:
    - label_studio_converter
    - opencv-python-headless
    - "git+https://github.com/facebookresearch/segment-anything.git"
    - "git+https://github.com/heartexlabs/label-studio-ml-backend.git"
